In [1]:
from __future__ import print_function

# Scikit-Criteria
## Multi-criterio integrado al stack científico de Python


**Juan Bautista Cabral**, 
**Nadia Ayelen Luczywo**,
**José Luis Zanazzi**

![afiliaciones](imgs/afiliaciones00.png)



## Antecedentes 

- Los procesos de **toma de decisiones** han sido un objeto de estudio.
- Bajo la denominación **Decisión Multicriterio Discreta**, proliferan métodos de soporte matemático aplicables para abordar el problema de evaluar un conjunto de alternativas en términos de una serie de criterios.
- Se avanza en el desarrollo de **Paquetes de Software** que soportan estos métodos.

## Variedad de software

- VIDMA (Korhonen), 
- Expert Choice (Saaty),Criterium, HIPRE 3+
- HIVIEW (Peterson),
- PROMCAL y GAIA (Brans y Mareschal ), 
- MACBETH (Bana e Costa y Vansnick),
- VIP (Dias y Climaco), 
- Decision Lab (Brans and Mareschal), 
- Otros 

### Vassilev y otros (2005)-   Zavadskas, Ustinovichius,y Peldschus (2003)


## Limitaciones de los paquetes Disponibles 
- El **volumen de datos** sobre el cual se puede operar.
- Tervonen (2012) enfatiza que las limitaciones se asocian con el soporte de un **único método** o un pequeño conjunto de métodos similares y con el **código cerrado** que requiere licencias pagas.
- Robitaille y otros (2013) destacan desarrollos heterogéneos **desaprovechan los esfuerzos comunitarios**.



## Intentos de selección de los paquetes de software más adecuados

- Li y Thomas (2014), proponen un enfoque metodológico para la selección de software DMD.
- Mustajoki y Marttunen (2013), avanzan en una propuesta similar de comparación de programas informá ticos para la decisión multi-criterio.
- Paradoja de la DMD.



### ¿Qué  posibilidades de superación existen ?

**Disponer de métodos multicriterio en un lenguaje multipropósito** de alto nivel que permitan:
- La integración de la DMD a arquitecturas mayores a las que están disponibles paquetes propietarios.
- El aprovechamiento de las herramientas científicas disponibles en lenguaje de programación de alto nivel. 
- La realización de implementaciones eficientes en complejidad espacial y temporal de los DMD.  
- Y  la migración de datos de un método a otro con la menor conversión de datos.

## Propuesta de superación



![afiliaciones](imgs/logo_medium.png)

   ## http://scikit-criteria.org

- Integrado al stack científico de Python.
- Implementa métodos mas comunes de DMD.
- Posee herramientas para implementar facilmente más metodos de DMD.
- Open Source

### ¿Por que Python?

- Lingua franca en ciencia de datos.
- Se dispone de librerías cientificas de todo tipo (pandas, nltk, astropy, scikit-bio, sympy, spark, etc)
- Es un lenguaje multipropósito.
- Open Source.

### Python es Robusto
![](imgs/excelproblem.png)

- Popular Mechanics: [http://goo.gl/rUlroh](http://www.popularmechanics.com/science/a22577/genetics-papers-excel-errors/)
- Paper: [Ziemann, M., Eren, Y., & El-Osta, A. (2016). Gene name errors are widespread in the scientific literature. Genome Biology, 17(1), 177.](http://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1044-7)

### Funcionalidades de Scikit-Criteria.

- Funcionalidades contenidas en **skcriteria.common** que incluye:
    - `skcriteria.common.norm`
    - `skcriteria.common.rank`
    - `skcriteria.common.util`

- Funcionalidades de métodos de DMD (`skcriteria.ahp`, `skcriteria.electre`, `skcriteria.moora`, `skcriteria.topsis`, `skcriteria.wprod`, `skcriteria.wsum`)   

## Aplicación

In [5]:
# cargamos el paquete de MOORA
from skcriteria.common.util import MAX, MIN
from skcriteria import moora

# definimos la matriz de preferencias donde cada fila es una
# alternativa y cada columna es un criterio.
mtx = [[33.95, 23.78, 11.45, 39.97, 29.44, 167.10, 3.852],
       [38.9, 4.17, 6.32, 0.01, 4.29, 132.52, 25.184],
       [37.59, 9.36, 8.23, 4.35, 10.22, 136.71, 10.845],
       [30.44, 37.59, 13.91, 74.08, 45.10, 198.34, 2.186],
       [36.21, 14.79, 9.17, 17.77, 17.06, 148.3, 6.610],
       [37.8, 8.55, 7.97, 2.35, 9.25, 134.83, 11.935]]

# vector de criterios: tiene la misma longitud que cantidad de 
# columnas tiene la matriz de preferencias. util.MIN representa 
# un criterio de minimo y util.MAX uno de maximo
criteria = [MIN, MIN, MIN, MIN, MAX, MIN, MAX]

# ahora aplicamos Multi-MOORA y obtenemos los valores
# del ranking de las alternativas
rank = moora.multimoora(mtx, criteria)
print("MOORA:", rank[1])

MOORA: [[5 4 5]
 [1 5 1]
 [3 1 3]
 [6 6 6]
 [4 2 4]
 [2 3 2]]


### Escalemos

In [11]:
import random
import numpy as np
from skcriteria import topsis
from skcriteria.common.util import MAX, MIN

crit_n = 1000
alt_n = 30000 
crit_half = crit_n / 2.
mtx = np.random.rand(alt_n, crit_n)
criteria = np.array([
        (MAX if idx > crit_half else MIN) for idx in range(crit_n)])

print("Forma:", mtx.shape)
print("Datos:", mtx.size)
print("Criterios:", criteria.shape)

Forma: (30000, 1000)
Datos: 30000000
Criterios: (1000,)


In [12]:
%%timeit -n1 -r1
rank = topsis.topsis(mtx, criteria)

1 loop, best of 1: 1.96 s per loop


## Conclusiones.

- Se ha diseñado un proyecto de software capaz de integrarse sobre la plataforma Python. 
- El diseño incluye herramientas comunes (paquete scikit.common) para la extensión de las funcionalidades preexistentes de manera de disminuir el esfuerzo en la realización de análisis multi-criterio.

**Trabajo futuro**:
Creación de una capa de abstracción orientada a objetos como la existente en Scikit-Learn para
facilitar el encapsulamiento de los datos de los métodos DMD.

### ¿Preguntas?

**Contactos:**

- Nadia <nluczywo@gmail.conm>
- Juan <jbc.develop@gmail.com>